I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scene1.rpy", line 38, in script
    $ response = LoveInterest.textResponse(LoveInterest.getResponse([0,0,2,0,0,0,0,0,0,0]))
  File "game/scene1.rpy", line 38, in <module>
    $ response = LoveInterest.textResponse(LoveInterest.getResponse([0,0,2,0,0,0,0,0,0,0]))
  File "game/script.rpy", line 46, in getResponse
    count = 0
AttributeError: 'LoveInterest' object has no attribute 'interest'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scene1.rpy", line 38, in script
    $ response = LoveInterest.textResponse(LoveInterest.getResponse([0,0,2,0,0,0,0,0,0,0]))
  File "C:\Users\JoshPC\Desktop\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\JoshPC\Desktop\Renpy\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/scene1.rpy", line 38, in <module>
    $ response = LoveInterest.textResponse(LoveInterest.getResponse([0,0,2,0,0,0,0,0,0,0]))
  File "game/script.rpy", line 46, in getResponse
    count = 0
AttributeError: 'LoveInterest' object has no attribute 'interest'

Windows-7-6.1.7601-SP1
Ren'Py 7.3.5.606
Love_BotDotIo 1.0
Sat Dec 12 21:51:39 2020
